import React, { useState } from "react";
import Header from "../Header/Header";

const Alerts = () => {
  const [filterSeverity, setFilterSeverity] = useState("All");

  const alerts = [
    {
      id: "MHW-2026-08A",
      type: "Marine Heatwave (MHW)",
      category: "Category II (Strong)",
      severityColor: "red",
      region: "South-Eastern Arabian Sea & Lakshadweep Sea",
      coordinates: "09.5° N - 12.0° N, 71.5° E - 74.5° E",
      details: "SST anomaly +2.4°C above baseline climatology. Degree Heating Days: 14.5 DHD.",
      impact: "Elevated bleaching threat to coral reef ecosystems and pelagic fish migration.",
      timestamp: "Issued: 2026-09-05 06:00 UTC",
      validity: "Valid through: 2026-09-08 18:00 UTC",
      agency: "INCOIS Marine Heatwave Watch",
    },
    {
      id: "SWELL-2026-14B",
      type: "High Wave & Swell Surge",
      category: "Moderate Hazard",
      severityColor: "amber",
      region: "South Tamil Nadu & Kerala Coastline",
      coordinates: "Kanyakumari, Kollam, Alappuzha (08.1° N - 09.5° N)",
      details: "Significant wave heights of 3.2m to 4.1m generated by Southern Ocean swells.",
      impact: "Potential coastal inundation during spring high tides. Fishermen advised caution.",
      timestamp: "Issued: 2026-09-05 04:00 UTC",
      validity: "Valid through: 2026-09-07 12:00 UTC",
      agency: "INCOIS Ocean State Forecast (OSF)",
    },
    {
      id: "SAR-2026-03C",
      type: "Search and Rescue (SAR) Drift",
      category: "Operational Advisory",
      severityColor: "blue",
      region: "Offshore Mumbai High Sector",
      coordinates: "19.42° N, 71.25° E",
      details: "Surface currents at 1.8 knots (0.92 m/s) heading 045° NE. Strong wind drift component.",
      impact: "Lagrangian particle drift trajectory computed for Indian Coast Guard search operations.",
      timestamp: "Issued: 2026-09-05 07:15 UTC",
      validity: "Updated: Hourly using ROMS current vectors",
      agency: "INCOIS Search & Rescue Aid Tool",
    },
    {
      id: "PFZ-2026-248",
      type: "Potential Fishing Zone (PFZ)",
      category: "Favorable Advisory",
      severityColor: "emerald",
      region: "Saurashtra Shelf & Gujarat Coast",
      coordinates: "20.5° N - 22.0° N, 68.5° E - 70.0° E",
      details: "Ocean thermal front between 27.5°C and 29.0°C co-located with high Chlorophyll-a (1.4 mg/m³).",
      impact: "High pelagic fish aggregation zone. Advisory transmitted via mobile mKRISHI & INCOIS portal.",
      timestamp: "Issued: 2026-09-05 02:00 UTC",
      validity: "Daily Forecast",
      agency: "INCOIS Fishery Advisory Services",
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      <main className="pt-28 px-6 pb-12 max-w-7xl mx-auto">
        {/* Header Title */}
        <div className="mb-6">
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 bg-teal-100 text-teal-800 text-xs font-bold rounded uppercase">
              Hazard Warning System
            </span>
            <span className="text-xs text-gray-500 font-medium">
              Disaster Management | INCOIS Ocean Hazards
            </span>
          </div>
          <h1 className="text-2xl font-bold text-gray-800">
            Alerts & Forecasts
          </h1>
          <p className="text-sm text-gray-600 max-w-3xl mt-1">
            Operational early warnings, marine heatwave detection, high swell surges, search-and-rescue (SAR) drift advisories, and disaster management support across India's EEZ.
          </p>
        </div>

        {/* Hazard Summary Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
          <div className="bg-white p-4 rounded-xl shadow-sm border border-red-100">
            <span className="text-xs font-semibold text-red-600 uppercase">Marine Heatwaves</span>
            <p className="text-2xl font-extrabold text-red-600 mt-1">1 Active (Cat-II)</p>
            <span className="text-xs text-gray-500">Arabian Sea & Lakshadweep</span>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-sm border border-amber-100">
            <span className="text-xs font-semibold text-amber-600 uppercase">Swell Surge Watch</span>
            <p className="text-2xl font-extrabold text-amber-600 mt-1">3.2m - 4.1m</p>
            <span className="text-xs text-gray-500">Kerala & Tamil Nadu Coast</span>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-sm border border-blue-100">
            <span className="text-xs font-semibold text-blue-600 uppercase">SAR Drift Operations</span>
            <p className="text-2xl font-extrabold text-blue-600 mt-1">1 Simulation Active</p>
            <span className="text-xs text-gray-500">Coast Guard Live Feed</span>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-sm border border-emerald-100">
            <span className="text-xs font-semibold text-emerald-600 uppercase">PFZ Advisories</span>
            <p className="text-2xl font-extrabold text-emerald-600 mt-1">4 Sectors Open</p>
            <span className="text-xs text-gray-500">Thermal Front Alignment</span>
          </div>
        </div>

        {/* Filter Controls */}
        <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 mb-6 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-2">
            <span className="text-gray-500 font-semibold">Filter Hazard Type:</span>
            {["All", "Marine Heatwave", "Swell Surge", "SAR Drift", "PFZ"].map((type) => (
              <button
                key={type}
                onClick={() => setFilterSeverity(type)}
                className={`px-3 py-1.5 rounded-lg font-medium transition-colors ${
                  filterSeverity === type
                    ? "bg-teal-600 text-white shadow-sm"
                    : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                }`}
              >
                {type}
              </button>
            ))}
          </div>
          <div className="text-gray-400">
            Automated ingestion from INCOIS-ROMS 1/12° Model & In-Situ Floats
          </div>
        </div>

        {/* Hazard Bulletins List */}
        <div className="space-y-4 mb-8">
          {alerts.map((a) => (
            <div
              key={a.id}
              className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 hover:shadow-md transition-shadow"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 border-b border-gray-100 pb-3 mb-3">
                <div className="flex items-center gap-3">
                  <span
                    className={`px-2.5 py-1 text-xs font-bold rounded uppercase ${
                      a.severityColor === "red"
                        ? "bg-red-100 text-red-800"
                        : a.severityColor === "amber"
                        ? "bg-amber-100 text-amber-800"
                        : a.severityColor === "blue"
                        ? "bg-blue-100 text-blue-800"
                        : "bg-emerald-100 text-emerald-800"
                    }`}
                  >
                    {a.category}
                  </span>
                  <h3 className="font-bold text-gray-800 text-base">{a.type}</h3>
                  <span className="text-xs font-mono text-gray-400">ID: {a.id}</span>
                </div>
                <div className="text-xs text-gray-500 font-medium">
                  {a.agency}
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div>
                  <p className="text-gray-500 font-medium">Region & Coordinates:</p>
                  <p className="font-semibold text-gray-800 mt-0.5">{a.region}</p>
                  <p className="font-mono text-gray-600 text-[11px]">{a.coordinates}</p>

                  <p className="text-gray-500 font-medium mt-2">Hazard Assessment:</p>
                  <p className="text-gray-700 mt-0.5">{a.details}</p>
                </div>

                <div>
                  <p className="text-gray-500 font-medium">Impact & Operational Advisory:</p>
                  <p className="text-gray-700 mt-0.5">{a.impact}</p>

                  <div className="mt-3 flex items-center justify-between pt-2 border-t border-gray-50 text-[11px]">
                    <span className="text-gray-500">{a.timestamp}</span>
                    <span className="font-semibold text-teal-700">{a.validity}</span>
                  </div>
                </div>
              </div>

              <div className="mt-4 pt-3 border-t border-gray-100 flex justify-end gap-2">
                <a
                  href="/explorer"
                  className="px-3 py-1.5 bg-teal-50 hover:bg-teal-100 text-teal-700 font-semibold rounded text-xs transition-colors"
                >
                  View in 3D Explorer &rarr;
                </a>
                <button className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 font-semibold rounded text-xs transition-colors">
                  Download Bulletin (PDF)
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Alerts;
